[preface]
== Foreword

This OGC Best Practice document details proposed configuration and
instantiation conventions for access to Earth Observation (EO) data developed
in the European Space Agency (ESA) funded project Evolution of EO Online Data
Access Services (EVO-ODAS).

It defines how to utilize WCS with EO products including generic conventions
and recommendations for data and metadata mapping and conversion which are to
be used in concrete tailoring for specific missions. It further considers how
to link to other services like CSW, WMS, and WPS.

Suggested additions, changes, and comments on this draft document are welcome
and encouraged. Such suggestions may be submitted by email message, by creating
an issue or a pull request at the
https://github.com/EOX-A/eo-data-access-bp[GitHub repository], or by making
suggested changes in an edited copy of this document.

_Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. The Open Geospatial Consortium
shall not be held responsible for identifying any or all such patent rights._

_Recipients of this document are requested to submit, with their comments,
notification of any relevant patent claims or other intellectual property
rights of which they may be aware that might be infringed by any implementation
of the standard set forth in this document, and to provide supporting
documentation._

== Introduction

TODO
