= OGC® EO Data Access Best Practice

== Scope

This OGC Best Practice document details configuration and instantiation
conventions for access to Earth Observation (EO) data. It defines how to
utilize EO-WCS with EO products including generic conventions and recommendations
for data and metadata mapping and conversion which are to be used in concrete
tailoring for specific missions. It further considers how to link to other
services like CSW, WMS, and WPS.

[#normative-references,reftext='2']
== Normative references

The following normative documents contain provisions that, through reference in
this text, constitute provisions of this specification. For dated references,
subsequent amendments to, or revisions of, any of these publications do not
apply. For undated references, the latest edition of the normative document
referred to applies.

OGC 06-121r9, _OGC Web Services Common Standard_, version 2.0

OGC 09-146r2, _OGC® Coverage Implementation Schema_ (renamed from _OGC®
GML Application Schema - Coverages_), version 1.0

OGC 09-110r4, _OGC® WCS 2.0 Interface Standard- Core: Corrigendum_, version
2.0

OGC 10-140r2, _OGC® Web Coverage Service 2.0 Interface Standard - Earth
Observation Application Profile_, version 1.1

OGC 11-053r1, _OGC® Web Coverage Service Interface Standard - CRS Extension_,
version 1.0
OGC 12-039, _OGC® Web Coverage Service Interface Standard - Scaling Extension_,
version 1.0

OGC 12-040, _OGC® Web Coverage Service Interface Standard - Range Subsetting
Extension_, version 1.0

OGC 12-049, _OGC® Web Coverage Service Interface Standard - Interpolation
Extension_, version 1.0

OGC 09-147r3, _OGC® Web Coverage Service 2.0 Interface Standard - KVP Protocol
Binding Extension - Corrigendum_, version 1.0

OGC 09-149r1, _OGC® Web Coverage Service 2.0 Interface Standard - XML/SOAP
Protocol Binding Extension_, version 1.0

OGC 12-100r1, _OGC® GML Application Schema - Coverages - GeoTIFF Coverage
Encoding Profile_, version 1.0

OGC 14-100r2, _OGC® CF-netCDF 3.0 encoding using GML Coverage Application
Schema_, version 2.0

OGC 12-108, _OGC® GML Application Schema - Coverages JPEG2000 Coverage Encoding
Extension_, version 1.0

OGC 10-157r4, _OGC® Earth Observation Metadata profile of Observations &
Measurements_, version 1.1

OGC 07-063r1, _OpenGIS® Web Map Services - Profile for EO Products_, version
0.3.3

_OpenSearch Parameter extension_, version 1.0 Draft 2, accessed 2016-43-20,
http://www.opensearch.org/Specifications/OpenSearch/Extensions/Parameter/1.0/Draft_2

OGC 13-026r8, _OGC® OpenSearch Extension for Earth Observation_, version 1.0

OGC 13-043, _OGC Download Service for Earth Observation Products Best
Practice_, version 1.0

== Terms and definitions

This document uses the standard terms defined in Subclause 5.3 of [OGC
06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the
structure and drafting of International Standards. In particular, the word
"shall" (not "must") is the verb form used to indicate a requirement to be
strictly followed to conform to this standard.

For the purposes of this document, the terms and definitions given in the above
references, particularly EO-WCS [10-140r2], apply. In addition, the following
terms and definitions apply. An arrow "->" indicates that the following term is
defined in this Clause.

=== Coverage

digital representation of a spatio-temporally varying phenomenon as defined in
[OGC 09-146r2]

=== Dataset

-> <<EO Coverage>>

NOTE: A Dataset usually represents observations obtained by satellite
instruments.

=== Dataset Series

collection of -> <<EO Coverage,EO Coverages>>

=== EO Coverage

Rectified Grid -> <<Coverage>> or Referenceable Grid -> <<Coverage>> having an
-> <<EO Metadata>> record and a WGS84 footprint

=== EO Metadata

-> <<EO Coverage,EO Coverage's>> metadata record

=== Stitched Mosaic

-> <<EO Coverage>> composed from subsets of one or more co-referenced ->
<<Dataset,Datasets>>

=== EO Product

An EO Product contains one or more related -> <<EO Product>> Datasets plus metadata
and optionally auxiliary data like -> <<EO Product>> Quicklooks.

=== EO Product Dataset

One or more files each containing one or more -> <<EO Coverage,EO Coverages>>.

=== EO Product Quicklook

A visual representation of a usually reduced -> <<EO Product>> Dataset encoded
in an image format. The -> <<EO Product>> Dataset may combine different bands.

=== Lineage record

Data structure documenting an operation that has been applied to the ->
<<Coverage>> it is part of

=== refers to

contains, in its -> <<EO Metadata>> element as defined in [OGC 10-157r4], the
-> <<EO Metadata>> element of

== Conventions

=== UML notation

Unified Modeling Language (UML) static structure diagrams appearing in this
specification are used as described in Subclause 5.2 of OGC Web Services Common
[OGC 06-121r9].

=== Data dictionary tables

The UML model data dictionary is specified herein in a series of tables. The
contents of the columns in these tables are described in Subclause 5.5 of [OGC
06-121r9]. The contents of these data dictionary tables are normative, including
any table footnotes.

=== Namespace prefix conventions

The following namespaces are used in this document. The prefix abbreviations
used constitute conventions used here, but are *not* normative. The namespaces
to which the prefixes refer are normative, however.

[#namespace_mappings,reftext='{table-caption} {counter:table-num}']
.Namespace mappings
[cols="^1,2*4",options="header"]
|===============================================================================
|Prefix |Namespace URI                          |Description
|xsd    |http://www.w3.org/2001/XMLSchema       |XML Schema namespace
|ows    |http://www.opengis.net/ows/2.0         |OWS Common 2.0
|gml    |http://www.opengis.net/gml/3.2         |GML 3.2.1
|gmlcov |http://www.opengis.net/gmlcov/1.0      |Coverages Implementation Schema
1.0
|wcs    |http://www.opengis.net/wcs/2.0         |WCS 2.0
|eop    |http://www.opengis.net/eop/2.1         |Earth Observation Metadata
Profile of Observations and Measurements
|opt    |http://www.opengis.net/opt/2.1         |Optical Earth Observation
Metadata Profile of Observations and Measurements (extension of eop)
|sar    |http://www.opengis.net/sar/2.1         |SAR Earth Observation Metadata
Profile of Observations and Measurements (extension of eop)
|wcseo  |http://www.opengis.net/wcs/wcseo/1.1   |WCS Application Profile - Earth
Observation 1.1
|scal   |http://www.opengis.net/wcs/scaling/1.0 (schema uses
http://www.opengis.net/WCS_service-extension_scaling/1.0) |WCS Scaling Extension
|int    |http://www.opengis.net/wcs/interpolation/1.0 (schema uses
http://www.opengis.net/WCS_service-extension_interpolation/1.0|WCS Interpolation
Extension
|crs    |http://www.opengis.net/wcs/crs/1.0     |WCS CRS Extension
|gmd    |http://www.isotc211.org/2005/gmd       |ISO 19139 Metadata
|gmi    |http://standards.iso.org/iso/19115/-2/gmi/1.0 or
http://www.isotc211.org/2005/gmi |ISO 19139-2 Metadata
|mdb    |http://standards.iso.org/iso/19115/-3/mdb/1.0 |ISO 19115-3 Metadata
|===============================================================================

=== Multiple representations

When multiple representations of the same information are given in a
specification document these are consistent. Should this not be the case then
this is considered an error, and the
http://schemas.opengis.net/wcs/wcseo/1.1/[XML Schema] shall take precedence.
