[#coverage-collections,reftext='7']
== Coverage Collections

WCS originally was perceived to give access to single coverages taken from a
flat set of coverage offerings in the server.

This approach was based on the classical subdivision into metadata services
(i.e., catalogs) and data services, connected through some loose coupling
(which effectively was never standardized beyond the recommendation to use
URLs).

With the progress of requirements and technology it is more and more considered
important to merge data and metadata perspectives with the vision of a common
integrated information space.

For WCS, this means in particular to further structure a server's offering of
coverages along various criteria.

Early on EO-WCS has provided a lead in this by introducing both uniform and
non-uniform coverage groupings together with dedicated search functionality
which is able to perform a focused search within coverage subsets.

With OGC Coverage Implementation Schema (CIS) 1.1 comes massively enhanced
support for structuring coverages. Therefore, a harmonization task has to be
accomplished to relate both concepts, which may well lead to an extension of
functionality for fully exploiting all benefits.

In the following subsections, we discuss EO-relevant grouping concepts, based
on CIS and EO-WCS.

[#grouping-of-associated-data,reftext='6.1']
=== Grouping of Associated Data

==== Overview

Modeling the grouped data as coverage itself would directly allow GetCoverage
requests but would require rather big changes to WCS. Thus we propose to follow
and extend the approach already established in EO- WCS and reuse the concept of
DatasetSeries.

As described in the section "Encoding of Multiple Coverages in One File" 3.1.2
above we propose to use `Reference` elements in `Metadata` elements also for
associated data. Together with the GetEOCoverageRequest operation and a
`mediaType` of `multipart/related` this could be suitable to be used for data
access to whole EO Products.

The first part of the multipart response would look like the example below but
additionally include `Reference` elements to the associated data inside
`Metadata` elements of the `DatasetSeries` element. Of course the second part
of the multipart response needs to include all the referenced files.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:EOCoverageSet numberMatched="3" numberReturned="3" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlcov="http://www.opengis.net/ mlcov/1.0" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:eop="http://www.opengis.net/eop/2.1" xmlns:om="http://www.opengis.net/om/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:RectifiedDataset gml:id="someEOCoverage1">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage1.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage1.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
      </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage1">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:RectifiedDataset gml:id="someEOCoverage2">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage2.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage2.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
        </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage2">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:DatasetSeries>
    <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
    <eop:Footprint gml:id="footprint_someDatasetSeries1">
    ...
    </eop:Footprint>
    <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    ...
    </gml:TimePeriod>
    <ows:Metadata>
      <wcseo:EOMetadata>
        <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
        <wcseo:lineage>
          <wcseo:referenceGetEOCoverageSet>
          <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related"/>
        </wcseo:referenceGetEOCoverageSet>
        <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
        </wcseo:lineage>
      </wcseo:EOMetadata>
    </ows:Metadata>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
    </wcseo:rectifiedDataset>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage2</wcs:CoverageId>
    </wcseo:rectifiedDataset>
  </wcseo:DatasetSeries>
</wcseo:EOCoverageSet>

An additional consideration is to harmonize this proposal with EO-O&M as
adopted by EO-WCS. EO-O&M is designed to define a catalog record for one EO
product including links to various raster or vector features like measurements,
browses, masks, etc.

TODO


[#collection-and-product-registration,reftext='6.2']
=== Collection and Product Registration

==== Overview

We propose to include a high level description of a HTTP REST API to
programmatic register collections and products in ODA Systems.

The API needs to specify the request and response structure as well as the
payloads. Both, particularly the payload, depend heavily on the functionality
available in concrete implementations. Thus we propose to evaluate the
suitability to specify collection and product registration including
suitability to specify a minimal set of services an ODA System has to support.

The GeoServer REST API 20 serves as basis for our proposal.

TODO


[#uniform-coverage-grouping,reftext='6.3']
=== Uniform Coverage Grouping

==== Overview

We propose to carefully review to which extent the forthcoming CIS 1.1 is
prepared for this.

The new partitioning functionality of CIS 1.1 requires all partitions to share
the same range type partitions which is exactly what is ask for in this item.
On the other side it requires partitions to not overlap which would require to
use real 3D coverages in order to group 2D EO coverages.

This needs to be further reviewed in order to harmonize with the concepts of
EO-WCS. In any case this might be best suited to be integrated and documented
in the solution to the "General Coverage Grouping" item detailed in section
3.3.1 below.

TODO
