[#coverage-collections,reftext='7']
== Coverage Collections

=== Motivation

WCS originally was perceived to give access to single coverages taken from a
flat set of coverage offerings on the server.

This approach was based on the classical subdivision into metadata services
(i.e., catalogs) and data services, connected through some loose coupling
(which effectively was never standardized beyond the recommendation to use
URLs).

With the progress of requirements and technology it is more and more considered
important to merge data and metadata perspectives with the vision of a common
integrated information space.

For WCS, this means in particular to further structure a server's offering of
coverages along various criteria.

Early on EO-WCS has provided a lead in this by introducing both uniform and
non-uniform coverage groupings together with dedicated search functionality
which is able to perform a focused search within coverage subsets.

With OGC Coverage Implementation Schema (CIS) 1.1 comes massively enhanced
support for structuring coverages. Therefore, a harmonization task has to be
accomplished to relate both concepts, which may well lead to an extension of
functionality for fully exploiting all benefits. One standardization
opportunity might be to generalize EO groupings, phase in CIS 1.1 concepts,
and establish a general WCS grouping extension.

A separate issue is how far recursion should be allowed: can a coverage
grouping be part of another coverage grouping, with unlimited nesting? While
the generality may be appealing it might pose severe extra complexity on
implementations.

In the following subsections, we discuss EO-relevant grouping concepts, based
on CIS and EO-WCS.

First, we address the special case of grouping coverages that share some
critical common properties. Next, we generalize this to arbitrary groupings of
coverages. Finally, we discuss registration issues.

[#uniform-coverage-grouping,reftext='6.3']
=== Uniform Coverage Grouping

==== Overview

Uniform Coverage Groupings represent sets of coverages which are homogeneous
enough that they can collectively appear as a single coverage from a WCS
perspective - in particular, such items are amenable to GetCoverage requests.
Aside from their positioning in space/time through the domain set there is no
other particular order defined on such coverage sets.

Concretely, the requirements on the coverages contained in a Uniform Coverage
Grouping are as follows (as a direct consequential of the definition of
coverage):

* all coverages contained shall have the same coverage type (i.e.,
  combinations of Rectified and Referenceable Grid, or MultiPoint Coverages,
  are prohibited);
* all coverages contained shall have the same range type (whereby it needs to
  be clarified when two range types are equal - for example, band names might
  be not constitutive while quantity, unit of measure, and nil values likely
  are);
* all coverages contained shall have the same resolution;
* all coverages contained shall have the same CRS in their domain set (note
  that this is not technically necessary for the boundedBy element which gives
  an informal, not necessarily minimal bounding box for a quick location
  determination);
* for each direct position (i.e., pixel) in the spatial domain of the Uniform
  Coverage Grouping there shall be exactly one range value - in other words,
  there shall be no "holes" and no duplicate pixel values.

In the context of EO-WCS, the coverage subtype `StitchedMosaic` implements the
Uniform Coverage Grouping.

==== A Concept for Uniform Coverage Groupings

TODO
    Idea: Derive DatasetSeries subtype where rangeType is fixed for all
    included coverages (maybe using schematron?). Make sure that this subtype
    is substitutable (substitutionGroup?) and instances still validate against
    EO-WCS 1.1 schemas.

==== Coverage Groupings in CIS 1.1 versus EO-WCS 1.1

CIS 1.1 offers a conformance class, `coverage-partitioning`, which allows
splitting a coverage into pieces - in other words, a coverage can be composed
from sub-coverages. This nesting of coverages actually is recursive, allowing
to establish hierarchically nested coverages.

As the new partitioning functionality of CIS 1.1 still defines a - partitioned
- coverage the same homogeneity criteria must hold as for "atomic" coverages:
they must have a common range type and domain set CRS, and common range
components ("bands", "variables") must not overlap. Note that the latter
constraint allows that different sub-coverages can overlap in their domain
set, but only when contributing to different range components; this way, bands
stored in single files, for example, can be assembled into multi-band
coverages.

EO-WCS, in comparison, allows coverages to overlap in a grouping, both in
DatasetSeries as well as StitchedMosaics. In the latter, StitchedMosaics, the
extra concept of a "contributing footprint" captures the overlap by indicating
which pixel contributes to the coverage - effectively, the contributing
footprint acts like a mask blanking out parts of a coverage, thereby achieving
a unique pixel for each position while retaining overlap information. This -
more involved - concept is not directly supported by the CIS 1.1 partitioning.

Obviously, there is a strong resemblance of concepts between CIS 1.1 and EO-
WCS 1.1. We therefore propose to carefully review forthcoming CIS 1.1 and how
far it accomplishes the grouping concepts proposed in this section.

Further, it should be noted that CIS 1.1 foresees a general object about which
no further normative constraints are made. Collections of coverages could be
derived from such objects if deemed feasible.

==== Modeling of Grouping Data and Operations

To capture as much of the semantics of such groupings - and hence ensure
integrity at the highest possible level - schematron can be used. The
following consistency constraints seem addressable:

* require the same coverage type, range type, CRS on all items contained in
  the grouping;
* require the same resolution (this information, though, is directly
  accessible only in CIS 1.1; in GMLCOV/CIS 1.0 it can only be computed
  through means beyond schematron); The final constraint - non-overlapping
  sub-coverages and no "holes" in super-coverage - can only be solved
  algorithmically, not through schematron - in particular, in presence of
  "contributing footprint" polygons as per EO-WCS.

In terms of operations, a Uniform Coverage Grouping needs to allow a
GetCoverage request. The result might be a "consolidated" flat coverage
reassembled from the sub-coverages, or a collection retaining those original
or cropped sub-coverages selected by the GetCoverage subsetting request.
Further, subset extraction is meaningful for obtaining particular sub-
coverages; in EO-WCS, this is accomplished through the DescribeEOCoverageSet
request type.

Note that CIS 1.1 allows any suitable container format (such as zip, SAFE,
etc.), thereby making delivery of "packages" representing Uniform Coverage
Groupings flexible and user-oriented.

=== General Grouping of Coverages

==== Concept

Generalizing the uniform grouping from above, coverages can be aggregated into
some topical information collection without any constraints of the elements
grouped, and without the need of them to form a single super-coverage.

For example, EO products are typically stored in single files, either using a
special binary EO format like NetCDF or ENVISAT N1, a special EO container
format like SAFE, e.g. Sentinel-2, or DIMAP, or a general container format
like TAR or ZIP. Sometimes EO products are stored as multiple files, e.g.,
sets of Landsat-8 files.

Modeling such grouped data as a coverage and allow GetCoverage requests would
conceptually break the coverage definition and would also overburden WCS,
rendering it impractical. Thus we propose to follow and extend the approach
already established in EO-WCS and enhance the concept of `DatasetSeries` to
incorporate the additional requirements that have come up to grasp more
application semantics:

* constrain participating coverages in their types; for example, a collection
  representing a product may consist of several hyperspectral images forming a
  timeseries, plus one binary mask; this can be expressed, for example, via
  schematron;
* restrict the range set, e.g., to particular bands; again, schematron can be
  used for this;
* Further, the OpenSearch EO Extension imposes a restriction in that it
  supports only two levels of grouping. Translated into the DatasetSeries
  modeling this means that a DatasetSeries cannot contain a DatasetSeries
  containing DatasetSeries itself. This can again be expressed through
  Schematron.

[#grouping-of-associated-data,reftext='7.1']
==== Encoding and Grouping of Associated Data

We now address the encoding of multiple coverages, potentially representing an
EO Product, in a package format like TAR or ZIP. Given the new operation
GetEOCoverageSet the only point missing is the inclusion of metadata on
package level.

Basically the EOMetadata element has been amended to be in the
`substitutionGroup` of `ows:AbstractMetaData` and the choice is extended by
references to ISO 19139 `MD_Metadata`, which can be substituted by ISO 19139-2
`MI_Metadata`, and ISO 19115-3 `MD_Metadata`. To recap, the already available
options are EO-O&M, or EOP as it is referred to sometimes, or by reference as
seen in the example below. A complete
https://github.com/Schpidi/eo-wcs/blob/evo-odas/schema/wcseo/examples/wcseo_responseDescribeEOCoverageSet_minimal.xml[example]
is provided with the EO-WCS standard.

These choices leave the option to use the concept of Dataset Series for
offering collections but also for EO Products. Although named Dataset Series
technically speaking it is a heterogeneous grouping of coverages and/or Dataset
Series and can thus be used for any other concept like an EO Product containing
multiple coverages with different resolutions as well.

The example below shows a complete `DatasetSeries` element including a
reference to further metadata.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:DatasetSeries xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchemainstance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
  <eop:Footprint gml:id="footprint_someDatasetSeries1">
    <eop:multiExtentOf>
      <gml:MultiSurface gml:id="multisurface_someDatasetSeries1" srsName="EPSG:4326">
        <gml:surfaceMembers>
          <gml:Polygon gml:id="polygon_someDatasetSeries1">
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>43.516667 2.1025 43.381667 2.861667 42.862778 2.65 42.996389 1.896944 43.516667 2.1025</gml:posList>
              </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMembers>
        </gml:MultiSurface>
    </eop:multiExtentOf>
  </eop:Footprint>
  <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    <gml:beginPosition>2008-03-13T00:00:00.000</gml:beginPosition>
    <gml:endPosition>2008-03-13T23:59:59.999</gml:endPosition>
  </gml:TimePeriod>
  <ows:Metadata>
    <wcseo:EOMetadata>
      <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
    </wcseo:EOMetadata>
  </ows:Metadata>
  <wcseo:rectifiedDataset>
    <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
  </wcseo:rectifiedDataset>
</wcseo:DatasetSeries>

Of course the mechanism of using `Reference` elements in `Metadata` elements
can also be used for associated data.

We propose to further investigate if a GetEOCoverageRequest together with a
`mediaType` of `multipart/related` is suitable to be used for data access to
whole EO Products. In a first step this will be verified using general
container formats as written above. The next step then is to investigate the
suitability of this approach also for special EO container formats like SAFE
and special binary EO formats like NetCDF or ENVISAT N1.

The first part of the multipart response would look like the example below but
additionally include `Reference` elements to the associated data inside
`Metadata` elements of the `DatasetSeries` element. Of course the second part
of the multipart response needs to include all the referenced files.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:EOCoverageSet numberMatched="3" numberReturned="3" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlcov="http://www.opengis.net/ mlcov/1.0" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:eop="http://www.opengis.net/eop/2.1" xmlns:om="http://www.opengis.net/om/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:RectifiedDataset gml:id="someEOCoverage1">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage1.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage1.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
      </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage1">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:RectifiedDataset gml:id="someEOCoverage2">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage2.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage2.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
        </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage2">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:DatasetSeries>
    <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
    <eop:Footprint gml:id="footprint_someDatasetSeries1">
    ...
    </eop:Footprint>
    <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    ...
    </gml:TimePeriod>
    <ows:Metadata>
      <wcseo:EOMetadata>
        <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
        <wcseo:lineage>
          <wcseo:referenceGetEOCoverageSet>
          <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related"/>
        </wcseo:referenceGetEOCoverageSet>
        <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
        </wcseo:lineage>
      </wcseo:EOMetadata>
    </ows:Metadata>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
    </wcseo:rectifiedDataset>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage2</wcs:CoverageId>
    </wcseo:rectifiedDataset>
  </wcseo:DatasetSeries>
</wcseo:EOCoverageSet>

An additional consideration is to harmonize this proposal with EO-O&M as
adopted by EO-WCS. EO-O&M is designed to define a catalog record for one EO
product including links to various raster or vector features like measurements,
browses, masks, etc.

[#collection-and-product-registration,reftext='6.2']
=== Collection and Product Registration

So far, access to coverages and groupings has been discussed. However, with
WCS-T Web-based maintenance of coverage offerings is possible, including
insertion, update, and deletion of coverages. This functionality might get
extended with maintenance operations on coverage collections.

Essentially, this would include creation and removal of collections, inclusion
of coverages into an existing collection as well as excluding selected
coverages, and maybe more.

Relevant existing approaches should be considered appropriately, such as the
GeoServer REST API 2.0.

TODO
