[#coverage-collections,reftext='7']
== Coverage Collections

WCS originally was perceived to give access to single coverages taken from a
flat set of coverage offerings on the server.

This approach was based on the classical subdivision into metadata services
(i.e., catalogs) and data services, connected through some loose coupling
(which effectively was never standardized beyond the recommendation to use
URLs).

With the progress of requirements and technology it is more and more considered
important to merge data and metadata perspectives with the vision of a common
integrated information space.

For WCS, this means in particular to further structure a server's offering of
coverages along various criteria.

Early on EO-WCS has provided a lead in this by introducing both uniform and
non-uniform coverage groupings together with dedicated search functionality
which is able to perform a focused search within coverage subsets.

With OGC Coverage Implementation Schema (CIS) 1.1 comes massively enhanced
support for structuring coverages. Therefore, a harmonization task has to be
accomplished to relate both concepts, which may well lead to an extension of
functionality for fully exploiting all benefits.

In the following subsections, we discuss EO-relevant grouping concepts, based
on CIS and EO-WCS.

[#grouping-of-associated-data,reftext='7.1']
=== Grouping of Associated Data

==== Overview

EO products are typically stored in single files, either using a special binary
EO format like NetCDF or ENVISAT N1, a special EO container format like SAFE,
e.g. Sentinel-2, or DIMAP, or a general container format like TAR or ZIP.
Sometimes EO products are stored as multiple files directly, e.g. Landsat-8.

Modeling the grouped data as coverage itself would directly allow GetCoverage
requests but would require rather big changes to WCS. Thus we propose to follow
and extend the approach already established in EO-WCS and reuse the concept of
Dataset Series.

As a first step, the encoding of multiple coverages, potentially representing
an EO Product, in a package format like TAR or ZIP is investigated. Given the
new operation GetEOCoverageSet the only point missing is the inclusion of
metadata on package level.

Basically the EOMetadata element has been amended to be in the
`substitutionGroup` of `ows:AbstractMetaData` and the choice is extended by
references to ISO 19139 `MD_Metadata`, which can be substituted by ISO 19139-2
`MI_Metadata`, and ISO 19115-3 `MD_Metadata`. To recap, the already available
options are EO-O&M, or EOP as it is referred to sometimes, or by reference as
seen in the example below. A complete
https://github.com/Schpidi/eo-wcs/blob/evo-odas/schema/wcseo/examples/wcseo_responseDescribeEOCoverageSet_minimal.xml[example]
is provided with the EO-WCS standard.

These choices leave the option to use the concept of Dataset Series for
offering collections but also for EO Products. Although named Dataset Series
technically speaking it is a heterogeneous grouping of coverages and/or Dataset
Series and can thus be used for any other concept like an EO Product containing
multiple coverages with different resolutions as well.

The example below shows a complete `DatasetSeries` element including a
reference to further metadata.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:DatasetSeries xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchemainstance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
  <eop:Footprint gml:id="footprint_someDatasetSeries1">
    <eop:multiExtentOf>
      <gml:MultiSurface gml:id="multisurface_someDatasetSeries1" srsName="EPSG:4326">
        <gml:surfaceMembers>
          <gml:Polygon gml:id="polygon_someDatasetSeries1">
            <gml:exterior>
              <gml:LinearRing>
                <gml:posList>43.516667 2.1025 43.381667 2.861667 42.862778 2.65 42.996389 1.896944 43.516667 2.1025</gml:posList>
              </gml:LinearRing>
              </gml:exterior>
            </gml:Polygon>
          </gml:surfaceMembers>
        </gml:MultiSurface>
    </eop:multiExtentOf>
  </eop:Footprint>
  <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    <gml:beginPosition>2008-03-13T00:00:00.000</gml:beginPosition>
    <gml:endPosition>2008-03-13T23:59:59.999</gml:endPosition>
  </gml:TimePeriod>
  <ows:Metadata>
    <wcseo:EOMetadata>
      <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
    </wcseo:EOMetadata>
  </ows:Metadata>
  <wcseo:rectifiedDataset>
    <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
  </wcseo:rectifiedDataset>
</wcseo:DatasetSeries>

Of course the mechanism of using `Reference` elements in `Metadata` elements
can also be used for associated data.

We propose to further investigate if a GetEOCoverageRequest together with a
`mediaType` of `multipart/related` is suitable to be used for data access to
whole EO Products. In a first step this will be verified using general
container formats as written above. The next step then is to investigate the
suitability of this approach also for special EO container formats like SAFE
and special binary EO formats like NetCDF or ENVISAT N1.

The first part of the multipart response would look like the example below but
additionally include `Reference` elements to the associated data inside
`Metadata` elements of the `DatasetSeries` element. Of course the second part
of the multipart response needs to include all the referenced files.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:EOCoverageSet numberMatched="3" numberReturned="3" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlcov="http://www.opengis.net/ mlcov/1.0" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:eop="http://www.opengis.net/eop/2.1" xmlns:om="http://www.opengis.net/om/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:RectifiedDataset gml:id="someEOCoverage1">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage1.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage1.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
      </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage1">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:RectifiedDataset gml:id="someEOCoverage2">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage2.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage2.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
        </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage2">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:DatasetSeries>
    <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
    <eop:Footprint gml:id="footprint_someDatasetSeries1">
    ...
    </eop:Footprint>
    <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    ...
    </gml:TimePeriod>
    <ows:Metadata>
      <wcseo:EOMetadata>
        <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
        <wcseo:lineage>
          <wcseo:referenceGetEOCoverageSet>
          <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related"/>
        </wcseo:referenceGetEOCoverageSet>
        <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
        </wcseo:lineage>
      </wcseo:EOMetadata>
    </ows:Metadata>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
    </wcseo:rectifiedDataset>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage2</wcs:CoverageId>
    </wcseo:rectifiedDataset>
  </wcseo:DatasetSeries>
</wcseo:EOCoverageSet>

An additional consideration is to harmonize this proposal with EO-O&M as
adopted by EO-WCS. EO-O&M is designed to define a catalog record for one EO
product including links to various raster or vector features like measurements,
browses, masks, etc.

[#collection-and-product-registration,reftext='6.2']
=== Collection and Product Registration

==== Overview

We propose to include a high level description of a HTTP REST API to
programmatic register collections and products in ODA Systems.

The API needs to specify the request and response structure as well as the
payloads. Both, particularly the payload, depend heavily on the functionality
available in concrete implementations. Thus we propose to evaluate the
suitability to specify collection and product registration including
suitability to specify a minimal set of services an ODA System has to support.

The GeoServer REST API 20 serves as basis for our proposal.

TODO


[#uniform-coverage-grouping,reftext='6.3']
=== Uniform Coverage Grouping

==== Overview

We propose to carefully review to which extent the forthcoming CIS 1.1 is
prepared for this. CIS 1.1 offers a conformance class, coverage-partitioning,
which allows splitting a coverage into pieces - in other words, a coverage can
be composed from sub-coverages. This nesting of coverages actually is recursive,
allowing to establish hierarchically nested coverages.

As the new partitioning functionality of CIS 1.1 still defines a - partitioned -
coverage the same homogeneity criteria hold as for "atomic" coverages: they must
have a common range type and common range components ("bands", "variables") must
not overlap. The latter means: different sub-coverages can overlap only when
contributing to different range components. EO-WCS, on the contrary, allows
coverages to overlap in a grouping, both in DatasetSeries as well as
StitchedMosaics.

In the latter, StitchedMosaics, the extra concept of a "contributing footprint"
captures the overlap by indicating which pixel contributes to the coverage -
effectively, the contributing footprint acts like a mask blanking out parts of a
coverage, thereby achieving a unique pixel for each position while retaining
overlap information. This - more involved - concept is not directly supported by
the CIS 1.1 partitioning.

TODO
    Idea: Derive DatasetSeries subtype where rangeType is fixed for all included
    coverages (maybe using schematron?). Make sure that this subtype is
    substitutable (substitutionGroup?) and instances still validate against EO-
    WCS 1.1 schemas.
