[#condense-coverage-description-information,reftext='8']
== Condense Coverage Description Information

=== Overview

OpenSearch is the designated EVO-ODAS endorsed search service. Thus we propose
to extend OpenSearch in a way to allow clients to specify the verbosity of the
answer using a new parameter named `view`. Several allowed values are defined
in that proposal ranging from `full` for everything to `geotime` for a very
limited view only including id, name, bbox, start, and end.

Additionally, there is the idea of adding histogram like functionality i.e.,
requesting summary information for defined buckets like months.

It should be noted that there exists an alternative approach to searching which
is based on XPath enabling traversal and subsetting of a server's XML
information hierarchy.

Although XPath looks like a promising approach there are some difficulties
particularly from an implementation point of view. In general, an XML document
can only be subsetted using XPath once it has been generated. This approach
wouldn't scale well on server implementations. Of course particular queries can
be computed on the fly but to allow generic XPath queries is quite challenging.

Another issue is, that XPath returns subsets of XML documents without
maintaining overlying hierarchy. While it is simple to retrieve a list of
coverage IDs for certain search criteria it is difficult if not impossible to
retrieve for the same list of coverages tailored coverage descriptions only
containing ID, phenomenon time, and footprint.

Further challenges arise when the query is supposed to contain time or spatial
subsetting.

OpenSearch and XPath are not competing, but complementary approaches:
OpenSearch empowers users to do human-centric search through keywords. XPath,
conversely, enables fine-grain drilling into the server's information structure
and, hence, is suitable in particular for machine-to-machine communication.

Both search types, therefore, are important for versatile coverage services. In
EVO-ODAS, the OpenSearch avenue will be elaborated.

TODO

=== OpenSearch `view` parameter

==== Objective

This proposal adds support for different levels of verbosity in OpenSearch
responses. Clients mainly need a complete and detailed view on the result set
but for example to show data availability on a time slider only a limited view
is needed. This limited view provides a great opportunity for performance
optimization, in response generation time on the server, in response size and
thus transfer time, and in response parsing time on the client.

The proposal adds a parameter named `view` to the OpenSearch URL template using
the OpenSearch Parameter extension. It further defines several mandatory and
optional options for predefined values for the new parameter including the
definition of the content of response. Additionally it leaves room to add
custom options as needed.

This shows an example of an `Url` element using the `view` parameter:

  <Url xmlns:param="http://a9.com/-/spec/opensearch/extensions/parameters/1.0/"
       xmlns:eo="http://a9.com/-/opensearch/extensions/eo/1.0/"
       type="application/atom+xml"
       rel="collection"
       template="http://example.com/atom?q={searchTerms}&amp;view={eo:view}">
    <param:Parameter name="view"
                     value="{eo:view}"
                     title="Verbosity of the response. Default: full"
                     pattern="full|brief|geotime"
                     minimum="0">
      <param:Option value="full" label="Complete and detailed view."/>
      <param:Option value="brief" label="Brief view to get a quick impression."/>
      <param:Option value="geotime" label="View to show data availability on a time slider."/>
    </param:Parameter>
  </Url>

==== `view` Parameter

The new `view` parameter reuses the namespace of the OGC® OpenSearch Extension
for Earth Observation [OGC 13-026r8]. It is used as `view={eo:view}` in the
template attribute of `Url` elements.

The following mandatory and optional option values are defined:

* `full` - mandatory - Complete and detailed view.
* `brief` - mandatory - Brief view to get a quick impression.
* `geotime` - optional - View to show data availability on a time slider.
* TODO

NOTE: Not all options have to necessarily be made available with each format.
The `geotime` option for example might be available with JSON or CSV formatting
but not with ATOM.

===== `full`

TODO: Use full EOP

===== `brief`

TODO: Check with CSW

===== `geotime`

Using this option returns the needed metadata to show data availability on a
time slider. The needed metadata are identifier, name, bounding box or
footprint in EPSG:4326, start time, and end time.

This is a response example in CSV format:

  "identifier","name","bbox","starttime","endtime"
  "1","Satellite image","(40,10,50,20)","2016-04-20T00:00:00Z","2016-04-20T23:59:59Z"

===== Custom options

TODO
