[#Condense Coverage Description Information,reftext='8']
== Condense Coverage Description Information

=== Overview

OpenSearch is the designated EVO-ODAS endorsed search service. Thus we propose
to extend OpenSearch in a way to allow clients to specify the verbosity of the
answer using a new parameter named `view`. Several allowed values are defined
in that proposal ranging from `full` for everything to `geotime` for a very
limited view only including id, name, bbox, start, and end.

Additionally, there is the idea of adding histogram like functionality i.e.,
requesting summary information for defined buckets like months.

It should be noted that there exists an alternative approach to searching which
is based on XPath enabling traversal and subsetting of a server's XML
information hierarchy.

Although XPath looks like a promising approach there are some difficulties
particularly from an implementation point of view. In general, an XML document
can only be subsetted using XPath once it has been generated. This approach
wouldn't scale well on server implementations. Of course particular queries can
be computed on the fly but to allow generic XPath queries is quite challenging.

Another issue is, that XPath returns subsets of XML documents without
maintaining overlying hierarchy. While it is simple to retrieve a list of
coverage IDs for certain search criteria it is difficult if not impossible to
retrieve for the same list of coverages tailored coverage descriptions only
containing ID, phenomenon time, and footprint.

Further challenges arise when the query is supposed to contain time or spatial
subsetting.

OpenSearch and XPath are not competing, but complementary approaches:
OpenSearch empowers users to do human-centric search through keywords. XPath,
conversely, enables fine-grain drilling into the server's information structure
and, hence, is suitable in particular for machine-to-machine communication.

Both search types, therefore, are important for versatile coverage services. In
EVO-ODAS, the OpenSearch avenue will be elaborated.

TODO
