[#Grouping of Associated Data,reftext='6']
== Grouping of Associated Data

=== Overview

Modeling the grouped data as coverage itself would directly allow GetCoverage
requests but would require rather big changes to WCS. Thus we propose to follow
and extend the approach already established in EO- WCS and reuse the concept of
DatasetSeries.

As described in the section "Encoding of Multiple Coverages in One File" 3.1.2
above we propose to use `Reference` elements in `Metadata` elements also for
associated data. Together with the GetEOCoverageRequest operation and a
`mediaType` of `multipart/related` this could be suitable to be used for data
access to whole EO Products.

The first part of the multipart response would look like the example below but
additionally include `Reference` elements to the associated data inside
`Metadata` elements of the `DatasetSeries` element. Of course the second part
of the multipart response needs to include all the referenced files.

[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<wcseo:EOCoverageSet numberMatched="3" numberReturned="3" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlcov="http://www.opengis.net/ mlcov/1.0" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:wcs="http://www.opengis.net/wcs/2.0" xmlns:wcseo="http://www.opengis.net/wcs/wcseo/1.1" xmlns:eop="http://www.opengis.net/eop/2.1" xmlns:om="http://www.opengis.net/om/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wcs/wcseo/1.1 http://schemas.opengis.net/wcs/wcseo/1.1/wcsEOAll.xsd">
  <wcseo:RectifiedDataset gml:id="someEOCoverage1">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage1.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage1.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
      </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage1">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:RectifiedDataset gml:id="someEOCoverage2">
    <gml:boundedBy>
    ...
    </gml:boundedBy>
    <gml:domainSet>
    ...
    </gml:domainSet>
    <gml:rangeSet>
      <gml:File>
        <gml:rangeParameters xlink:arcrole="fileReference" xlink:href="cid:coverage.meta4;someEOCoverage2.tif" xlink:role="http://www.opengis.net/spec/GMLCOV_geotiff-coverages/1.0/conf/geotiff-coverage" />
        <gml:fileReference>cid:coverage.meta4;someEOCoverage2.tif</gml:fileReference>
        <gml:fileStructure />
        <gml:mimeType>image/tiff</gml:mimeType>
        </gml:File>
    </gml:rangeSet>
    <gmlcov:rangeType>
    ...
    </gmlcov:rangeType>
    <gmlcov:metadata>
      <gmlcov:Extension>
        <wcseo:EOMetadata>
          <eop:EarthObservation gml:id="eop_someEOCoverage2">
          ...
          </eop:EarthObservation>
          <wcseo:lineage>
            <wcseo:referenceGetEOCoverageSet>
              <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related" />
            </wcseo:referenceGetEOCoverageSet>
            <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
          </wcseo:lineage>
        </wcseo:EOMetadata>
      </gmlcov:Extension>
    </gmlcov:metadata>
  </wcseo:RectifiedDataset>
  <wcseo:DatasetSeries>
    <wcseo:DatasetSeriesId>someDatasetSeries1</wcseo:DatasetSeriesId>
    <eop:Footprint gml:id="footprint_someDatasetSeries1">
    ...
    </eop:Footprint>
    <gml:TimePeriod gml:id="someDatasetSeries1_timeperiod">
    ...
    </gml:TimePeriod>
    <ows:Metadata>
      <wcseo:EOMetadata>
        <ows:Reference xlink:href="http://www.someCatalogue.org/eop-metadatafrom-someDatasetSeries1" xlink:role="http://standards.iso.org/iso/19115/-3/mdb/1.0" xlink:title="ISO 19115-3 Metadata" />
        <wcseo:lineage>
          <wcseo:referenceGetEOCoverageSet>
          <ows:Reference xlink:href="http://www.someWCS.org?SERVICE=WCS&amp;VERSION=2.0.1&amp;REQUEST=GetEOCoverageSet&amp;EOID=someDatasetSeries1&amp;PACKAGEFORMAT=application/metalink4+xml&amp;MEDIATYPE=multipart/related"/>
        </wcseo:referenceGetEOCoverageSet>
        <gml:timePosition>2016-05-17T12:25:40Z</gml:timePosition>
        </wcseo:lineage>
      </wcseo:EOMetadata>
    </ows:Metadata>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage1</wcs:CoverageId>
    </wcseo:rectifiedDataset>
    <wcseo:rectifiedDataset>
      <wcs:CoverageId>someEOCoverage2</wcs:CoverageId>
    </wcseo:rectifiedDataset>
  </wcseo:DatasetSeries>
</wcseo:EOCoverageSet>

An additional consideration is to harmonize this proposal with EO-O&M as
adopted by EO-WCS. EO-O&M is designed to define a catalog record for one EO
product including links to various raster or vector features like measurements,
browses, masks, etc.

TODO
