== Scope

This OGC Best Practice document details configuration and instantiation
conventions for access to Earth Observation (EO) data. It defines how to
utilize EO-WCS with EO products including generic conventions and recommendations
for data and metadata mapping and conversion which are to be used in concrete
tailoring for specific missions. It further considers how to link to other
services like CSW, WMS, and WPS.

=== Future Work

Suggested additions, changes, and comments on this draft document are welcome
and encouraged. Such suggestions may be submitted by email message to the
document editor or contributors named above, by creating an issue or a pull
request at the https://github.com/EOX-A/eo-data-access-bp[GitHub repository],
or by making suggested changes in an edited copy of this document.

Presently, this document is a living document until officially submitted to
OGC seeking formal adoption. Below is a list of items that are currently
worked on or that could be worked on in future activities.

==== <<cross-service-interaction,Cross Service Interaction>>

Detailing how to structure the data offered in the various services as well as
how to explicitly link between those services. The OGC services under
consideration are: OpenSearch, WMS, WMTS, WCS, and DS-EO.

There is a proposal available in the: "EVO-ODAS Recommendation on building a
discovery interface using OpenSearch Technical Note (EVOODAS-TN-GEO-4112
version 1.3.0 from 2017-10-24)" developed in parallel by GeoSolutions on how
to address this item for linking from OpenSearch to the other services.

For the other linking mechanisms a proposal still needs to be worked on.

==== <<coverage-collections,Coverage Collections>>

Adding support for typical EO concepts like multi-resolution products or cloud
masks to OGC services including registration in those services.

We propose to carefully review forthcoming CIS 1.1 against EO-WCS 1.1
particularly how far it accomplishes the grouping concepts proposed in there.

Further we propose to review the idea to derive DatasetSeries subtypes as
described in the relevant section below.

Finally the <<collection-and-product-registration,Collection and Product
Registration>> using a HTTP REST API for programmatic collection and product
registration probably based on WCS-T needs to be drafted.

Product registration has been tested in the EVO-ODAS initiative by defining
the contents of a `product.zip` package and sending them to the HTTP REST API
for registration. The contents are defined as:

* `product.json` - Product metadata in GeoJSON format.
* `granules.json` - Metadata linking to the actual data again in GeoJSON
  `format.
* `thumbnail.jpg` - An optional thumbnail image.
* `metadata.xml` -  Optional EO-O&M formated metadata.
* `owsLinks.json` - Optional links to OGC services including template tags in
  `JSON format.
* `description.html` - Optional description in HTML format.

==== <<condense-coverage-description-information,Condense Coverage Description Information>>

Applying performance optimizations to facilitate and enable modern web based
applications.

The OpenSearch SRU (Search and Retrieval via URL) extension needs to be
investigated for suitability. Alternatively the already drafted usage of a new
parameter named `view` needs to be further pursued and elaborated.

Additionally the proposal for the item Explore Coverages by Dimension right
below holds some interesting concepts also for this item like the GetHistogram
request.

==== Explore Coverages by Dimension

There is a proposal for compact domain inspection and histogram generation
available in the: "EVO-ODAS Multidimensional WMTS domain discovery Technical
Note (EVOODAS-TN-GEO-4111_WMTS version 1.0 from 2016-05-23)". This work has
already been presented to OGC's WMS SWG. We propose to pursue the adoption of
this document in the WMS SWG and in parallel validate and document the usage
in the EO domain in the present Best Practice document.

==== <<wcs-masking-extension,WCS Masking Extension>>

Proposing support for retrieving non-rectangular subsets of coverages from
WCS.

This needs to be drafted.

==== Filtering via Common Query Language (CQL)

Sometimes it would be interesting to being able to filter the responses from
certain services like for example OpenSearch and WMS in the same way. This
means that in the WMS GetMap request only those products are rendered that are
also returned via an OpenSearch query. A nice way to accomplish this is
allowing to use a specific parameter called for examples `cql_filter` in all
services where this functionality is needed. The value of this parameter could
hold any valid CQL query and thus when using the same query on different
services accomplishes the desired behavior.

This solution has been tested and verified to some extend in the EVO-ODAS
initiative. The next step would be formal documentation that could be part of
this Best Practice document.

==== Integration of Access and Processing Services

Access and processing services both need to be located near the storage
facilities to improve the performance when working on large EO time series.
Thus these services are often available on top of the same data. It needs to
be investigated how access services can effectively utilize and interface with
the processing infrastructure and algorithms for user-defined information
extraction. Furthermore a standardized procedure and interface is needed to
reference EO products from discovery and access services as input to
processing, so that a user can execute a process based on the results of a
previous product search.

An idea to investigate is to use OpenSearch queries as exchange mechanism,
i.e., to specify data input for WPS or WCS processing via WCPS.

==== Cloud Optimized GeoTIFF (COG)

We recommend to review a recent proposal named Cloud Optimized GeoTIFF (COG,
http://www.cogeo.org) for suitability as an alternative way to download EO
data.

==== Caching and tiling in WCS

For certain use cases it is desirable to optimally support clients as well as
intermediate nodes on the web in caching responses to WCS requests. Caching is
an implementation detail most HTTP software has natively build in using a
certain set of HTTP headers to control behavior. However, this caching is not
available when using query strings as in KVP encoding or POST requests. Thus,
for caching, the invocation via REST potentially using JSON encoding is of
high interest.

In OGC discussions about a Web Coverage Tile Service (WCTS) have started in a
dedicated working group. Most likely this service will include considerations
about caching which should be evaluated and harmonized.

==== Asynchronous Requests Extension

Support for asynchronous requests for example for large downloads via
GetCoverage or uploads via InsertCoverage that potentially need long
processing times on the server is currently not available in WCS.

We propose to review the simple approach taken in DS-EO for suitability and
develop a WCS extension to support asynchronous requests. Note that as per OAB
and agreed by WPS experts, a bridging WCS-WPS Application Profile is not a
suitable option.

==== <<conclusions,Summary>>

A <<conclusions,summary>> for the intended use and benefits of EO-WCS 1.1 is
planned to be added.
