:Title: OGC® EO Data Access Best Practice
:titletext: OGC® EO Data Access Best Practice
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter: pygments

= {title}

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: TBD
|Approval Date: TBD
|Publication Date: TBD
|External identifier of this OGC(R) document: http://www.opengis.net/doc/BP/eo-data-access-bp
|Internal reference number of this OGC(R) document: 16-118
|URL for this OGC® document: https://eox-a.github.io/eo-data-access-bp/
|PDF version: https://eox-a.github.io/eo-data-access-bp/index.pdf
|Version: 0.0.1draft
|Category: OGC(R) Best Practice
|Editor: Stephan Meißl
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2016, 2017 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

[cols = "^", frame = "none"]
|===
|*Warning*
|===

This document is not an OGC Standard. This document is distributed for review and comment. This document is subject to change without notice and may not be referred to as an OGC Standard.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

[width = "50%", grid = "none"]
|===
|Document type: OGC® Best Practice
|Document subtype: Profile
|Document stage: Draft proposed version
|Document language: English
|===

<<<
License Agreement

[small]#Permission is hereby granted by the Open Geospatial Consortium, ("Licensor"), free of charge and subject to the terms set forth below, to any person obtaining a copy of this Intellectual Property and any associated documentation, to deal in the Intellectual Property without restriction (except as set forth below), including without limitation the rights to implement, use, copy, modify, merge, publish, distribute, and/or sublicense copies of the Intellectual Property, and to permit persons to whom the Intellectual Property is furnished to do so, provided that all copyright notices on the intellectual property are retained intact and that each person to whom the Intellectual Property is furnished agrees to the terms of this Agreement.#

[small]#If you modify the Intellectual Property, all copies of the modified Intellectual Property must include, in addition to the above copyright notice, a notice that the Intellectual Property includes modifications that have not been approved or adopted by LICENSOR.#

[small]#THIS LICENSE IS A COPYRIGHT LICENSE ONLY, AND DOES NOT CONVEY ANY RIGHTS UNDER ANY PATENTS THAT MAY BE IN FORCE ANYWHERE IN THE WORLD.#

[small]#THE INTELLECTUAL PROPERTY IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE INTELLECTUAL PROPERTY WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE INTELLECTUAL PROPERTY WILL BE UNINTERRUPTED OR ERROR FREE. ANY USE OF THE INTELLECTUAL PROPERTY SHALL BE MADE ENTIRELY AT THE USER’S OWN RISK. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR ANY CONTRIBUTOR OF INTELLECTUAL PROPERTY RIGHTS TO THE INTELLECTUAL PROPERTY BE LIABLE FOR ANY CLAIM, OR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM ANY ALLEGED INFRINGEMENT OR ANY LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR UNDER ANY OTHER LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH THE IMPLEMENTATION, USE, COMMERCIALIZATION OR PERFORMANCE OF THIS INTELLECTUAL PROPERTY.#

[small]#This license is effective until terminated. You may terminate it at any time by destroying the Intellectual Property together with all copies in any form. The license will also terminate if you fail to comply with any term or condition of this Agreement. Except as provided in the following sentence, no such termination of this license shall require the termination of any third party end-user sublicense to the Intellectual Property which is in force as of the date of notice of such termination. In addition, should the Intellectual Property, or the operation of the Intellectual Property, infringe, or in LICENSOR's sole opinion be likely to infringe, any patent, copyright, trademark or other right of a third party, you agree that LICENSOR, in its sole discretion, may terminate this license without any compensation or liability to you, your licensees or any other party. You agree upon termination of any kind to destroy or cause to be destroyed the Intellectual Property together with all copies in any form, whether held by you or by any third party.#

[small]#Except as contained in this notice, the name of LICENSOR or of any other holder of a copyright in all or part of the Intellectual Property shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Intellectual Property without prior written authorization of LICENSOR or such copyright holder. LICENSOR is and shall at all times be the sole entity that may authorize you or any third party to use certification marks, trademarks or other special designations to indicate compliance with any LICENSOR standards or specifications. This Agreement is governed by the laws of the Commonwealth of Massachusetts. The application to this Agreement of the United Nations Convention on Contracts for the International Sale of Goods is hereby expressly excluded. In the event any provision of this Agreement shall be deemed unenforceable, void or invalid, such provision shall be modified so as to make it valid and enforceable, and as so modified the entire Agreement shall remain in full force and effect. No decision, action or inaction by LICENSOR shall be construed to be a waiver of any rights or remedies available to it.#

<<<
toc::[]

== Abstract

This OGC Best Practice document provides conventions and recommendations on how
to utilize OGC services to provide access to Earth Observation data.

== Keywords

ogcdoc, eo, earth observation, data access, wcs, eo-wcs

== Submitting organizations

The following organizations have submitted this Best Practice to the
Open GeoSpatial Consortium, Inc.:

* https://eox.at[EOX IT Services GmbH]
* http://www.dlr.de[German Aerospace Center (DLR)]
* http://www.geo-solutions.it[GeoSolutions S.A.S.]
* http://www.esa.int[European Space Agency (ESA)]
* http://www.jacobs-university.de[Jacobs University Bremen]

== Document Contributor Contact Points

All questions regarding this document should be directed to the editor or the
contributors.

[options="header"]
|=============================================================================
|Name                                   |Organization
|Stephan Meißl <stephan.meissl@eox.at>  |https://eox.at[EOX IT Services GmbH]
|Peter Baumann <p.baumann@jacobs-university.de> |
http://www.jacobs-university.de[Jacobs University Bremen]
|Andrea Aime <andrea.aime@geo-solutions.it> |
http://www.geo-solutions.it[GeoSolutions S.A.S.]
|=============================================================================

== Changes to the OGC ® Abstract Specification

The OGC ® Abstract Specification does not require any changes to accommodate
the technical contents of this (part of this) document.

== Future Work

Suggested additions, changes, and comments on this draft document are welcome
and encouraged. Such suggestions may be submitted by email message to the
document editor or contributors named above, by creating an issue or a pull
request at the https://github.com/EOX-A/eo-data-access-bp[GitHub repository],
or by making suggested changes in an edited copy of this document.

Presently, this document is a living document until officially submitted to
OGC seeking formal adoption. Below is a list of items that are currently
worked on or that could be worked on in future activities.

=== <<cross-service-interaction,Cross Service Interaction>>

Detailing how to structure the data offered in the various services as well as
how to explicitly link between those services. The OGC services under
consideration are: OpenSearch, WMS, WMTS, WCS, and DS-EO.

There is a proposal available in the: "EVO-ODAS Recommendation on building a
discovery interface using OpenSearch Technical Note (EVOODAS-TN-GEO-4112
version 1.3.0 from 2017-10-24)" developed in parallel by GeoSolutions on how
to address this item for linking from OpenSearch to the other services.

For the other linking mechanisms a proposal still needs to be worked on.

=== <<coverage-collections,Coverage Collections>>

Adding support for typical EO concepts like multi-resolution products or cloud
masks to OGC services including registration in those services.

We propose to carefully review forthcoming CIS 1.1 against EO-WCS 1.1
particularly how far it accomplishes the grouping concepts proposed in there.

Further we propose to review the idea to derive DatasetSeries subtypes as
described in the relevant section below.

Finally the <<collection-and-product-registration,Collection and Product
Registration>> using a HTTP REST API for programmatic collection and product
registration probably based on WCS-T needs to be drafted.

Product registration has been tested in the EVO-ODAS initiative by defining
the contents of a `product.zip` package and sending them to the HTTP REST API
for registration. The contents are defined as:

* `product.json` - Product metadata in GeoJSON format.
* `granules.json` - Metadata linking to the actual data again in GeoJSON
  `format.
* `thumbnail.jpg` - An optional thumbnail image.
* `metadata.xml` -  Optional EO-O&M formated metadata.
* `owsLinks.json` - Optional links to OGC services including template tags in
  `JSON format.
* `description.html` - Optional description in HTML format.

=== <<condense-coverage-description-information,Condense Coverage Description Information>>

Applying performance optimizations to facilitate and enable modern web based
applications.

The OpenSearch SRU (Search and Retrieval via URL) extension needs to be
investigated for suitability. Alternatively the already drafted usage of a new
parameter named `view` needs to be further pursued and elaborated.

Additionally the proposal for the item Explore Coverages by Dimension right
below holds some interesting concepts also for this item like the GetHistogram
request.

=== Explore Coverages by Dimension

There is a proposal for compact domain inspection and histogram generation
available in the: "EVO-ODAS Multidimensional WMTS domain discovery Technical
Note (EVOODAS-TN-GEO-4111_WMTS version 1.0 from 2016-05-23)". This work has
already been presented to OGC's WMS SWG. We propose to pursue the adoption of
this document in the WMS SWG and in parallel validate and document the usage
in the EO domain in the present Best Practice document.

=== <<wcs-masking-extension,WCS Masking Extension>>

Proposing support for retrieving non-rectangular subsets of coverages from
WCS.

This needs to be drafted.

=== Filtering via Common Query Language (CQL)

Sometimes it would be interesting to being able to filter the responses from
certain services like for example OpenSearch and WMS in the same way. This
means that in the WMS GetMap request only those products are rendered that are
also returned via an OpenSearch query. A nice way to accomplish this is
allowing to use a specific parameter called for examples `cql_filter` in all
services where this functionality is needed. The value of this parameter could
hold any valid CQL query and thus when using the same query on different
services accomplishes the desired behavior.

This solution has been tested and verified to some extend in the EVO-ODAS
initiative. The next step would be formal documentation that could be part of
this Best Practice document.

=== Integration of Access and Processing Services

Access and processing services both need to be located near the storage
facilities to improve the performance when working on large EO time series.
Thus these services are often available on top of the same data. It needs to
be investigated how access services can effectively utilize and interface with
the processing infrastructure and algorithms for user-defined information
extraction. Furthermore a standardized procedure and interface is needed to
reference EO products from discovery and access services as input to
processing, so that a user can execute a process based on the results of a
previous product search.

An idea to investigate is to use OpenSearch queries as exchange mechanism,
i.e., to specify data input for WPS or WCS processing via WCPS.

=== Cloud Optimized GeoTIFF (COG)

We recommend to review a recent proposal named Cloud Optimized GeoTIFF (COG,
http://www.cogeo.org) for suitability as an alternative way to download EO
data.

=== Caching and tiling in WCS

For certain use cases it is desirable to optimally support clients as well as
intermediate nodes on the web in caching responses to WCS requests. Caching is
an implementation detail most HTTP software has natively build in using a
certain set of HTTP headers to control behavior. However, this caching is not
available when using query strings as in KVP encoding or POST requests. Thus,
for caching, the invocation via REST potentially using JSON encoding is of
high interest.

In OGC discussions about a Web Coverage Tile Service (WCTS) have started in a
dedicated working group. Most likely this service will include considerations
about caching which should be evaluated and harmonized.

=== Asynchronous Requests Extension

Support for asynchronous requests for example for large downloads via
GetCoverage or uploads via InsertCoverage that potentially need long
processing times on the server is currently not available in WCS.

We propose to review the simple approach taken in DS-EO for suitability and
develop a WCS extension to support asynchronous requests. Note that as per OAB
and agreed by WPS experts, a bridging WCS-WPS Application Profile is not a
suitable option.

=== <<conclusions,Summary>>

A <<conclusions,summary>> for the intended use and benefits of EO-WCS 1.1 is
planned to be added.

include::00_introduction.adoc[]

:numbered:

include::01-04_base.adoc[]
include::05_cross-service-interaction.adoc[]
include::06_rangetype-description-enhancements.adoc[]
include::07_coverage_collections.adoc[]
include::08_condense-coverage-description-information.adoc[]
include::09_wcs-masking-extension.adoc[]
include::10_conclusions.adoc[]

:numbered!:

include::bibliography.adoc[]

:numbered:

//include::annexes/a_ats.adoc[]
include::annexes/b_revision-history.adoc[]
